name: jwallpaper
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  provider: ^6.0.1
  like_button: ^2.0.4
  shared_preferences: ^2.0.13
  eva_icons_flutter: ^3.0.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_spinkit: ^5.0.0
  get_it: ^7.2.0
  json_annotation: ^4.1.0
  shimmer: ^2.0.0
  freezed_annotation: ^1.1.0
  bloc: ^8.0.2
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.0.1
  scroll_to_index: ^2.1.1
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  waterfall_flow: ^3.0.1
  url_launcher: ^6.1.3
  android_path_provider: ^0.3.0
  permission_handler: ^10.0.0
  share_plus: ^4.0.8
  photo_view:
    # custom photo_view with better gesture recognition
    git: https://github.com/robertodoering/photo_view.git
  gallery_saver: ^2.3.2
  flare_flutter: ^3.0.0
  
dev_dependencies:
  build_runner: ^2.0.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.1


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/flare/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Light.ttf
          weight: 300
        - asset: assets/fonts/Comfortaa-Regular.ttf
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

    - family: NotoSans
      # used as a fallback font
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700